version: '3.8'

services:
  flask-app:
    build: flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENVIRONMENT=development
    volumes:
      - .:/app

  nginx-server:
    build: nginx
    ports:
      - "80:80"