apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: dev-cli
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
