apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev-cli
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gabrieldesir/lab5_nginx
        ports:
        - containerPort: 80
        - containerPort: 5000
